#!/usr/bin/env python3
"""
Phase 1: Ghidra Headless 모드로 모든 함수 디컴파일

Ghidra의 analyzeHeadless를 사용하여 모든 함수를 자동으로 디컴파일합니다.
"""

import os
import re
import json
import time
from datetime import datetime
from pathlib import Path

# 출력 디렉토리
OUTPUT_DIR = Path("output")
DECOMPILED_DIR = OUTPUT_DIR / "decompiled"
DOCS_DIR = OUTPUT_DIR / "docs"
CHECKPOINT_DIR = OUTPUT_DIR / "checkpoints"

# 심볼 파일
SYMBOLS_FILE = Path("spice86-dumps/E06625593A0E4A57396DF846E686BC063D03668F1CFB6B8D6B75E14FFCE5D07A/spice86dumpGhidraSymbols.txt")

def parse_symbols_file():
    """Spice86 심볼 파일에서 함수 목록 추출"""

    functions = []

    with open(SYMBOLS_FILE, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            parts = line.split()
            if len(parts) >= 3:
                name = parts[0]
                address = parts[1]
                type_flag = parts[2]

                # 함수만 추출 (type_flag == 'f')
                if type_flag == 'f':
                    functions.append({
                        "name": name,
                        "address": address
                    })

    return functions

def create_ghidra_script(functions):
    """Ghidra 스크립트 생성 (Java)"""

    script_content = """//Ghidra Batch Decompiler Script
//Auto-generated by Phase 1 extraction
//@category Analysis

import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.program.model.address.Address;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionManager;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;

public class BatchDecompile extends GhidraScript {

    @Override
    public void run() throws Exception {

        DecompInterface decompiler = new DecompInterface();
        decompiler.openProgram(currentProgram);

        String outputDir = "/Users/joejeon/Documents/develop/Double Dragon/output/decompiled/";
        File dir = new File(outputDir);
        if (!dir.exists()) {
            dir.mkdirs();
        }

        FunctionManager funcMgr = currentProgram.getFunctionManager();

        int total = 0;
        int success = 0;
        int failed = 0;

        println("Starting batch decompilation...");
        println("Output directory: " + outputDir);
        println("");

        for (Function func : funcMgr.getFunctions(true)) {
            total++;

            String funcName = func.getName();
            Address funcAddr = func.getEntryPoint();

            println("[" + total + "] Decompiling: " + funcName + " at " + funcAddr);

            try {
                DecompileResults results = decompiler.decompileFunction(func, 30, monitor);

                if (results != null && results.decompileCompleted()) {
                    String cCode = results.getDecompiledFunction().getC();

                    // C 파일 저장
                    File cFile = new File(outputDir + funcName + ".c");
                    PrintWriter writer = new PrintWriter(new FileWriter(cFile));
                    writer.println("// Function: " + funcName);
                    writer.println("// Address: " + funcAddr);
                    writer.println("// Decompiled: " + new java.util.Date());
                    writer.println("");
                    writer.println(cCode);
                    writer.close();

                    // JSON 메타데이터
                    File jsonFile = new File(outputDir + funcName + ".json");
                    PrintWriter jsonWriter = new PrintWriter(new FileWriter(jsonFile));
                    jsonWriter.println("{");
                    jsonWriter.println("  \\"name\\": \\"" + funcName + "\\",");
                    jsonWriter.println("  \\"address\\": \\"" + funcAddr + "\\",");
                    jsonWriter.println("  \\"size\\": " + func.getBody().getNumAddresses());
                    jsonWriter.println("}");
                    jsonWriter.close();

                    success++;
                    println("  ✓ Success");
                } else {
                    failed++;
                    println("  ✗ Failed to decompile");
                }
            } catch (Exception e) {
                failed++;
                println("  ✗ Error: " + e.getMessage());
            }
        }

        println("");
        println("============================================================");
        println("Batch Decompilation Complete!");
        println("============================================================");
        println("Total functions: " + total);
        println("Success: " + success);
        println("Failed: " + failed);
        println("Success rate: " + (success * 100.0 / total) + "%");

        decompiler.dispose();
    }
}
"""

    script_file = Path("ghidra-scripts/BatchDecompile.java")
    script_file.parent.mkdir(parents=True, exist_ok=True)

    with open(script_file, 'w') as f:
        f.write(script_content)

    print(f"✅ Ghidra 스크립트 생성: {script_file}")
    return script_file

def run_ghidra_headless(script_file):
    """Ghidra Headless 모드 실행"""

    ghidra_dir = "/opt/homebrew/Cellar/ghidra/11.4.2/libexec"
    project_dir = Path("ghidra-project").absolute()
    project_name = "DoubleDragon"

    # analyzeHeadless 명령
    cmd = [
        f"{ghidra_dir}/support/analyzeHeadless",
        str(project_dir),
        project_name,
        "-process", "DDMAIN.EXE",
        "-scriptPath", "ghidra-scripts",
        "-postScript", "BatchDecompile.java",
        "-noanalysis"  # 이미 분석 완료
    ]

    print("\n" + "=" * 70)
    print("Ghidra Headless 실행...")
    print("=" * 70)
    print(f"명령어: {' '.join(cmd)}")
    print("")

    import subprocess

    # Java 환경변수 설정
    env = os.environ.copy()
    env['JAVA_HOME'] = "/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home"
    env['PATH'] = f"{env['JAVA_HOME']}/bin:{env['PATH']}"

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=3600,  # 1시간 타임아웃
            env=env
        )

        print(result.stdout)
        if result.stderr:
            print("STDERR:")
            print(result.stderr)

        return result.returncode == 0

    except subprocess.TimeoutExpired:
        print("❌ 타임아웃! 1시간 초과")
        return False
    except Exception as e:
        print(f"❌ 오류: {e}")
        return False

def main():
    """Phase 1 메인 실행"""

    print("\n" + "=" * 70)
    print("Phase 1: 전체 코드 추출")
    print("=" * 70)

    start_time = datetime.now()

    # Step 1: 함수 목록 파싱
    print("\n📋 Step 1: Spice86 심볼 파일 파싱...")
    functions = parse_symbols_file()
    print(f"✅ 총 {len(functions)}개 함수 발견")

    # 함수 일부 출력
    print("\n처음 10개 함수:")
    for i, func in enumerate(functions[:10], 1):
        print(f"  {i}. {func['name']} ({func['address']})")

    # Step 2: Ghidra 스크립트 생성
    print("\n🔧 Step 2: Ghidra 디컴파일 스크립트 생성...")
    script_file = create_ghidra_script(functions)

    # Step 3: Ghidra Headless 실행
    print("\n🚀 Step 3: Ghidra Headless 모드로 디컴파일 실행...")
    success = run_ghidra_headless(script_file)

    end_time = datetime.now()
    duration = (end_time - start_time).total_seconds()

    # 결과 확인
    decompiled_files = list(DECOMPILED_DIR.glob("*.c"))

    print("\n" + "=" * 70)
    if success:
        print("✅ Phase 1 완료!")
    else:
        print("⚠️ Phase 1 완료 (일부 오류 발생)")
    print("=" * 70)
    print(f"\n📊 통계:")
    print(f"   - 총 함수: {len(functions)}개")
    print(f"   - 디컴파일 완료: {len(decompiled_files)}개 C 파일")
    print(f"   - 소요 시간: {duration:.1f}초 ({duration/60:.1f}분)")

    # 체크포인트 저장
    report = {
        "phase": 1,
        "timestamp": datetime.now().isoformat(),
        "stats": {
            "total_functions": len(functions),
            "decompiled_files": len(decompiled_files),
            "duration_seconds": duration
        },
        "functions": functions[:20]  # 처음 20개만 저장
    }

    checkpoint_file = CHECKPOINT_DIR / "phase1.json"
    with open(checkpoint_file, 'w') as f:
        json.dump(report, f, indent=2, ensure_ascii=False)

    print(f"\n✅ 체크포인트 저장: {checkpoint_file}")

if __name__ == "__main__":
    main()
