//Ghidra Batch Decompiler Script
//Auto-generated by Phase 1 extraction
//@category Analysis

import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.program.model.address.Address;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionManager;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;

public class BatchDecompile extends GhidraScript {

    @Override
    public void run() throws Exception {

        DecompInterface decompiler = new DecompInterface();
        decompiler.openProgram(currentProgram);

        String outputDir = "/Users/joejeon/Documents/develop/Double Dragon/output/decompiled/";
        File dir = new File(outputDir);
        if (!dir.exists()) {
            dir.mkdirs();
        }

        FunctionManager funcMgr = currentProgram.getFunctionManager();

        int total = 0;
        int success = 0;
        int failed = 0;

        println("Starting batch decompilation...");
        println("Output directory: " + outputDir);
        println("");

        for (Function func : funcMgr.getFunctions(true)) {
            total++;

            String funcName = func.getName();
            Address funcAddr = func.getEntryPoint();

            println("[" + total + "] Decompiling: " + funcName + " at " + funcAddr);

            try {
                DecompileResults results = decompiler.decompileFunction(func, 30, monitor);

                if (results != null && results.decompileCompleted()) {
                    String cCode = results.getDecompiledFunction().getC();

                    // C 파일 저장
                    File cFile = new File(outputDir + funcName + ".c");
                    PrintWriter writer = new PrintWriter(new FileWriter(cFile));
                    writer.println("// Function: " + funcName);
                    writer.println("// Address: " + funcAddr);
                    writer.println("// Decompiled: " + new java.util.Date());
                    writer.println("");
                    writer.println(cCode);
                    writer.close();

                    // JSON 메타데이터
                    File jsonFile = new File(outputDir + funcName + ".json");
                    PrintWriter jsonWriter = new PrintWriter(new FileWriter(jsonFile));
                    jsonWriter.println("{");
                    jsonWriter.println("  \"name\": \"" + funcName + "\",");
                    jsonWriter.println("  \"address\": \"" + funcAddr + "\",");
                    jsonWriter.println("  \"size\": " + func.getBody().getNumAddresses());
                    jsonWriter.println("}");
                    jsonWriter.close();

                    success++;
                    println("  ✓ Success");
                } else {
                    failed++;
                    println("  ✗ Failed to decompile");
                }
            } catch (Exception e) {
                failed++;
                println("  ✗ Error: " + e.getMessage());
            }
        }

        println("");
        println("============================================================");
        println("Batch Decompilation Complete!");
        println("============================================================");
        println("Total functions: " + total);
        println("Success: " + success);
        println("Failed: " + failed);
        println("Success rate: " + (success * 100.0 / total) + "%");

        decompiler.dispose();
    }
}
